# Generated by Django 6.0.1 on 2026-01-07 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOrder',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Updated On')),
                ('order_id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Order Id')),
                ('currency', models.CharField(default='INR', max_length=5, verbose_name='Currency')),
                ('order_amount', models.PositiveBigIntegerField(default=0)),
                ('is_payment_done', models.BooleanField(default=False, verbose_name='Payment Done')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_orders', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Updated On')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('cashfree_customer_id', models.CharField(max_length=100, verbose_name='Cashfree Customer Id')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Updated On')),
                ('amount', models.PositiveBigIntegerField(default=0)),
                ('status', models.CharField(choices=[('started', 'started'), ('failed', 'failed'), ('done', 'done')], max_length=7, verbose_name='Transaction Status')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_transaction', to='app_accounts.userorder', verbose_name='User Order')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_transactions', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
