# Generated by Django 6.0.1 on 2026-01-07 11:18

import app_accounts.models
import functools
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0002_otpmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpmodel',
            name='otp',
            field=models.CharField(default=functools.partial(app_accounts.models.random_string), max_length=6, verbose_name='OTP'),
        ),
    ]
